- name: Create Mastodon user
  user:
    name: "{{ mastodon_user }}"
    createhome: true
    shell: /bin/bash
    home: "{{ mastodon_home }}"

- name: Adding user nginx to mastodon user
  user:
    name: 'nginx'
    groups: mastodon
    append: yes
  when:
    - ansible_os_family == "RedHat"

- name: Allow mastodon groupusers to enter {{ mastodon_home }}
  ansible.builtin.file:
    path: "{{ mastodon_home }}"
    mode: '0710'
  when:
    - ansible_os_family == "RedHat"