- name: Create Mastodon user
  user:
    name: "{{ mastodon_user }}"
    createhome: true
    shell: /bin/bash
    home: "{{ mastodon_home }}"

- name: Ensure nginx can enter {{ mastodon_home }}
  ansible.builtin.file:
    path: "{{ mastodon_home }}"
    mode: '0701'
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "Rocky"