---

#Speeds up the provisioning process as cache is not updated for every single package.
- name: Update package manager cache before installing packages.
  become: yes
  package:
    update_cache: yes

- name: Install Postgres packages
  become: yes
  package:
    name: "{{ item.package }}"
    update_cache: no
    #This makes the package module non-OS generic
    #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
    #    cache_valid_time: 3600
    #    state: latest
    #    install_recommends: no
  with_items: "{{ postgres.packages }}"
