---

- name: Bootstrapping
  gather_facts: False
  hosts: all
  roles:
    - init

- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - postgres
  tags:
    - postgres

- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - redis
  tags:
    - redis

- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - web
  tags:
    - web