name: test
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "base/**"
      - "meta/**"
      - "templates/**"
      - "ansible.cfg"
      - "goss.yaml"
      - "requirements.txt"
      - "Vagrantfile"
      - "variables.yml"
      - "vars.yaml"
  pull_request:

jobs:
  test:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        os: [focal, jammy, rhel8, rhel9]
    steps:
      - uses: actions/checkout@v3
      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run tests in Vagrant
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          vagrant up ${{ matrix.os }}
