name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        os: [focal, jammy, rhel8, rhel9]
    steps:
      - uses: actions/checkout@v3
      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Run tests in Vagrant
        run: vagrant up ${{ matrix.os }}
